# Generated by Django 4.1 on 2022-08-25 19:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('account_type', models.CharField(max_length=20, null=True)),
                ('account_balance', models.IntegerField()),
                ('account_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, null=True)),
                ('symbol', models.CharField(max_length=5, null=True)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=15, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('age', models.PositiveSmallIntegerField()),
                ('password', models.CharField(max_length=20, null=True)),
                ('id_number', models.IntegerField(null=True)),
                ('nationality', models.CharField(max_length=20, null=True)),
                ('date_of_registration', models.DateTimeField(default=datetime.datetime.now)),
                ('profile_picture', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=20, null=True)),
                ('pin', models.IntegerField(null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_currency', to='wallet.currency')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_customer', to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_amount', models.IntegerField()),
                ('transaction_number', models.CharField(max_length=20, null=True)),
                ('transaction_type', models.CharField(max_length=20, null=True)),
                ('transaction_charge', models.IntegerField()),
                ('date_and_time', models.DateTimeField(default=datetime.datetime.now)),
                ('reciept', models.CharField(max_length=20, null=True)),
                ('destination_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_account', to='wallet.account')),
                ('origin_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_account', to='wallet.account')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Thirdparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('account_number', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=20, null=True)),
                ('amount', models.IntegerField()),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thirdparty_currency', to='wallet.currency')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_transaction', to='wallet.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('message', models.CharField(max_length=50, null=True)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('points', models.IntegerField()),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_recipient', to='wallet.customer')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_transaction', to='wallet.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(max_length=20, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('bill_number', models.CharField(max_length=20, null=True)),
                ('amount', models.IntegerField()),
                ('receipt_file', models.FileField(upload_to='')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_customer', to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(choices=[('E', 'Email'), ('P', 'Push')], max_length=20, null=True)),
                ('title', models.CharField(max_length=20, null=True)),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('R', 'Read'), ('U', 'Unread')], max_length=20, null=True)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipient', to='wallet.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=20, null=True)),
                ('amount', models.IntegerField()),
                ('interest_rate', models.IntegerField()),
                ('loan_balance', models.IntegerField()),
                ('guarantor', models.CharField(max_length=20, null=True)),
                ('payment_due_date', models.DurationField()),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('card_name', models.CharField(max_length=20, null=True)),
                ('date_issued', models.DateTimeField(default=datetime.datetime.now)),
                ('card_type', models.CharField(choices=[('C', 'Credit Card'), ('D', 'Debit Card')], max_length=20, null=True)),
                ('expiry_date', models.IntegerField()),
                ('security_code', models.IntegerField()),
                ('issuer', models.CharField(choices=[('v', 'Visa Card'), ('M', 'Master Card')], max_length=20, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_account', to='wallet.account')),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_wallet', to='wallet.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_wallet', to='wallet.wallet'),
        ),
    ]
