# Generated by Django 4.0.6 on 2022-08-19 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_account_recipient_reward_wallet_transaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='receipt_file',
            new_name='profilepicture',
        ),
    ]
