# Generated by Django 4.0.6 on 2022-09-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_customer_address_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_of_registration',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
