# Generated by Django 4.0.6 on 2022-09-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_customer_date_of_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='nationality',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
