# Generated by Django 4.0.6 on 2022-09-13 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_customer_id_number_customer_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
    ]
