# Generated by Django 4.0.6 on 2022-08-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_rename_profilepicture_recipient_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='destination_account',
            field=models.IntegerField(),
        ),
    ]
