# Generated by Django 4.0.6 on 2022-08-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_transaction_destination_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='profile_picture',
            new_name='profilepicture',
        ),
    ]
